# Generated by Django 4.2 on 2023-06-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
